### ISSUE TITLE
Recommend different default port other than 5000

### ISSUE THREAD

**Issue by peal333** [rjmacarthy/twinny-api#4]
I was able to get this running on Apple Silicon but port 5000 is used for Control Center for AirPlay functionality on Mac.

**Comment by rjmacarthy** [comment]
I updated the default port to use 7000, thanks for the suggestion @panupans.

**Comment by vamsig7** [comment]
@panupans  Can you share the changes you made to make this work in m1? I am facing these issues
1.) if device type is 'cpu' -> engine is posting "POST /v1/engines/codegen/completions HTTP/1.1" 200 OK", but vscode extension keep on spinning with message  "twinny thinking"
2.) if device type is 'cuda'  docker is closing with 135 exit code

Sorry if this is wrong place to ask
